behaviors:
  RocketBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 5000
