behaviors:
  RocketBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 1000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.90
        strength: 1.0
    max_steps: 40000000
    time_horizon: 512
    summary_freq: 5000
