behaviors:
  Rocket:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.7
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.5
      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: /home/david/Code/Uni/pem-ki/unity/iRocketLanding24/Assets/ML-Agents/demos/ExpertRocket001.demo
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 1000
